### ISSUE TITLE
Retina display issues

### ISSUE THREAD

**Issue by choult** [MeltwaterArchive/editor#22]
There appear to be misalignments in the sprites used for Retina display.

**Comment by michaldudek** [comment]
Could you be more specific? I've tested on iPhone, iPad and MBP and everything seems fine. Could you provide a screenshot or exactly where should I look (I may not be seeing something)?

**Comment by choult** [comment]
We get exactly the same issue in Chrome, Safari and Firefox on a 15" Retina MacBook Pro running OSX 10.8.3:

![Screen Shot 2013-04-17 at 11 20 26](https://f.cloud.github.com/assets/738776/390701/b69d4736-a748-11e2-9f44-a93aff34318e.png)

**Comment by michaldudek** [comment]
Can you try here http://datasift.neverblanddev.co.uk/ ?

Make sure your embedded version have all updated assets. I see by inspecting your CSS that your CSS file is not up to date:

This is yours:

![image](https://f.cloud.github.com/assets/802141/391170/9e601b90-a75b-11e2-8bdf-51e1e667dc42.png)

This is updated:

![image](https://f.cloud.github.com/assets/802141/391172/ba6f9220-a75b-11e2-8dac-75668beb1e77.png)

(Notice the background-size).

Also, for some reason your version doesn't seem to use retina sprite.

**Comment by michaldudek** [comment]
Any updates on this?

**Comment by choult** [comment]
I believe this to be fixed, thanks for the help (sorry to leave the ticket open)
