### ISSUE TITLE
Jquery 1.9+

### ISSUE THREAD

**Issue by salehsed** [MeltwaterArchive/editor#23]
Hi 

Is there any plan to upgrade the jquery to 1.9+
we are experiencing issues with jquery 1.9 and it doesn't work with it .

TypeError: Cannot read property 'msie' of undefined

Thanks

**Comment by choult** [comment]
Hi @salehsed,

Thanks for the report - we're aware of the issue and currently working to update the code; it relates to the deprecation of browser detection in jQuery itself:

http://api.jquery.com/jQuery.browser/

Hopefully it shouldn't be too long until we get this resolved.

Chris

**Comment by michaldudek** [comment]
Thanks @salehsed for reporting this issue. It has now been fixed so you can update your code to the latest version.

**Comment by salehsed** [comment]
Thanks 
Is it available in https://github.com/datasift/editor/tree/master/minified (the last commit is from 3 months ago)?

**Comment by michaldudek** [comment]
Good spot, forgot to merge pull request ;) It's there now.
