### ISSUE TITLE
Missing assets 

### ISSUE THREAD

**Issue by salehsed** [MeltwaterArchive/editor#26]
Hi

After updating to latest version (jquery 1.9+)
There are some missing assets 
'''
images/ui-bg_highlight-soft_100_eeeeee_1x100.png              404 (Not Found) jquery.js:7124
images/ui-bg_gloss-wave_35_f6a828_500x100.png               404 (Not Found) jquery.js:7124
images/ui-bg_glass_100_f6f6f6_1x400.png                           404 (Not Found) jquery.js:7124
'''

**Comment by michaldudek** [comment]
Hi @salehsed, I just updated with a fix for this. Those images weren't even used in the query builder anyway, but now they won't be showing 404 errors either ;)

**Comment by salehsed** [comment]
@michaldudek thanks
