### ISSUE TITLE
Tagging 

### ISSUE THREAD

**Issue by salehsed** [MeltwaterArchive/editor#29]
Hi 

What's the plan for tagging and releasing a stable version 

thanks 
@Salehsed

**Comment by choult** [comment]
Hi @salehsed - we're just coming to a decision on our tagging approach and I'll drop you a line on this issue when we've done it.

Chris

**Comment by michaldudek** [comment]
The editor is now tagged at 2.1.2 and also available on [Bower](https://github.com/bower/bower):

`bower install jcsdl`

**Comment by choult** [comment]
Hi @salehsed, as you can see we're now tagging the Query Builder to match the JCSDL version as the major and point versions; we'll tick up the third ordinal as we make fixes.

Chris

**Comment by salehsed** [comment]
Thanks @chrishoult
