### ISSUE TITLE
Error:The given JCSDL did not verify!

### ISSUE THREAD

**Issue by salehsed** [MeltwaterArchive/editor#37]
Hi 

We used query builder to create following CSDL, But after reload ing same CSDL into in, we saw following error : 
"Error:The given JCSDL did not verify!"

// JCSDL_MASTER c46c6f5e9bf8e27467238a0d7f47d876 AND
// JCSDL_VERSION 2.1
// JCSDL_START 1d4292a06f3a0fd35a8bbccb32f34c37 augmentation.demographic.location-city,contains_any,40-11 1
demographic.location.city contains_any "Los Angeles"
// JCSDL_END
AND
// JCSDL_START e71764977f28a41ea3cc71a5834586e4 augmentation.salience.content.entities-type,contains_any,45-11 2
salience.content.entities.type contains_any "Los Angeles"
// JCSDL_END
AND
// JCSDL_START 4b4514579f46bd3a0f02d9ceef4e8e7a interaction.content,contains_any,34-38 3
interaction.content contains_any "DWTS,dancingabc,dancing with the stars"
// JCSDL_END
// JCSDL_MASTER_END

**Comment by michaldudek** [comment]
Hi,

I have tested this CSDL and it loads just fine into my query builder. Check here: http://datasift.github.io/editor/

What version of the query builder are you using? Have you updated to the latest?

**Comment by michaldudek** [comment]
Hi @salehsed , any updates on this? Did you manage to work it out?

**Comment by salehsed** [comment]
Updating to latest version resolved the issue , thanks
