### ISSUE TITLE
How to prevent certain keywords in search

### ISSUE THREAD

**Issue by salehsed** [MeltwaterArchive/editor#40]
Hi 

While using visual query builder, we found out that someone can put a single character in search term , which can cause a huge data load in stream. is there any way to prevent it.

e.g. final CSDL => 

interaction.content  contains_any " "

thanks

**Comment by salehsed** [comment]
Is it possible to check the inputed valued before adding it to filter list

**Comment by michaldudek** [comment]
Hey,

We don't think we want to invalidate something like this - it is still a valid CSDL code and someone may want to be able to put a single character there (for whatever reason).
