### ISSUE TITLE
Dragging issue with jQuery UI 1.10.3

### ISSUE THREAD

**Issue by artsyca** [MeltwaterArchive/editor#41]
Steps to reproduce:
- Load an embedded editor with jQuery UI 1.10.3
- Create some filters.
- Choose 'Advanced logic' 
- Attempt to drag or add parens
- UI breaks.

Expected behaviour:
- UI should be draggable.

This seems to be an issue with jQuery UI's deprecation of isOverAxis, and returns the following error:

```
Object #<Object> has no method 'isOverAxis
```

Please see screenshot, attached.

![screen shot 2013-10-05 at 3 53 43](https://f.cloud.github.com/assets/364015/1274324/4b8350d6-2d93-11e3-9226-1a24388c7053.png)

**Comment by artsyca** [comment]
Oh wow, thank you so much. At the time of filing this issue I wasn't fully aware of the setup but I was thinking it might be a case of updating the included jQuery UI. Much obliged for your immediate response!

**Comment by michaldudek** [comment]
No problemo ;)
