### ISSUE TITLE
JCSDL not Verifying

### ISSUE THREAD

**Issue by slowgreenturtle** [MeltwaterArchive/editor#51]
The following CSDL verifies in the advanced editor, but does not in the editor. Ideas?

// JCSDL_MASTER ed0648a7329a1aa481d196dc75251288 ((1 | 2) & (3 | 4)) & 5
// JCSDL_VERSION 2.1
((
// JCSDL_START eee4359313491c9ff3a486a9be864e7f twitter.text,contains_any,27-3 1
twitter.text contains_any "SUV"
// JCSDL_END
OR
// JCSDL_START e9d078d1770aea4d6bbab1700b9cf5f3 twitter.text,contains_any,27-3 2
twitter.text contains_any "suv"
// JCSDL_END
) AND (
// JCSDL_START d551dc5b60177178930b60ac40bf27db twitter.text,contains_any,27-3 3
twitter.text contains_any "bmw"
// JCSDL_END
OR
// JCSDL_START 0cc02a0926b258078310f98a70730fae twitter.text,contains_any,27-3 4
twitter.text contains_any "BMW"
// JCSDL_END
)) AND
// JCSDL_START 7486bd013a0302464ee361a3a2dbd538 augmentation.demographic.sex,equals,20-6 5
demographic.sex == "female"
// JCSDL_END
// JCSDL_MASTER_END

**Comment by michaldudek** [comment]
Hi,

Indeed, there is a bug when you save the JCSDL while having advanced logic editor open on the manual editor. I have submitted a patch that fixes it and once the editor is updated it will not require any additional action from your side.

Thanks for reporting.

**Comment by michaldudek** [comment]
In the meantime, if you need it, here is a fixed version of the JCSDL code you pasted, that will validate properly in the current version:

```
// JCSDL_MASTER 6ac230d7f26234059c0ffdc350325736 ((1|2)&(3|4))&5
// JCSDL_VERSION 2.1
((
// JCSDL_START eee4359313491c9ff3a486a9be864e7f twitter.text,contains_any,27-3 1
twitter.text contains_any "SUV"
// JCSDL_END
OR
// JCSDL_START e9d078d1770aea4d6bbab1700b9cf5f3 twitter.text,contains_any,27-3 2
twitter.text contains_any "suv"
// JCSDL_END
) AND (
// JCSDL_START d551dc5b60177178930b60ac40bf27db twitter.text,contains_any,27-3 3
twitter.text contains_any "bmw"
// JCSDL_END
OR
// JCSDL_START 0cc02a0926b258078310f98a70730fae twitter.text,contains_any,27-3 4
twitter.text contains_any "BMW"
// JCSDL_END
)) AND
// JCSDL_START 7486bd013a0302464ee361a3a2dbd538 augmentation.demographic.sex,equals,20-6 5
demographic.sex == "female"
// JCSDL_END
// JCSDL_MASTER_END
```
